# fly.toml app configuration file generated for institute-restless-flower-67 on 2025-08-25T11:14:51+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crm-system-institute'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
