// <auto-generated />
using System;
using Institute.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Institute.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250606143410_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Institute.Entity.DepartmentEntity", b =>
                {
                    b.Property<string>("DepartmentName")
                        .HasColumnType("text");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LecturerCount")
                        .HasColumnType("integer");

                    b.HasKey("DepartmentName");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentName = "Математика",
                            Head = "Іванов І.І.",
                            LecturerCount = 10
                        },
                        new
                        {
                            DepartmentName = "Фізика",
                            Head = "Петров П.П.",
                            LecturerCount = 8
                        },
                        new
                        {
                            DepartmentName = "Хімія",
                            Head = "Сідоров С.С.",
                            LecturerCount = 7
                        },
                        new
                        {
                            DepartmentName = "Біологія",
                            Head = "Кузнецов К.К.",
                            LecturerCount = 5
                        },
                        new
                        {
                            DepartmentName = "Інформатика",
                            Head = "Смирнов С.С.",
                            LecturerCount = 12
                        });
                });

            modelBuilder.Entity("Institute.Entity.EmployeeEntity", b =>
                {
                    b.Property<int>("PassportNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PassportNumber"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ContractStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsWarVeteran")
                        .HasColumnType("boolean");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TIN")
                        .HasColumnType("integer");

                    b.Property<int>("WorkExperience")
                        .HasColumnType("integer");

                    b.HasKey("PassportNumber");

                    b.HasIndex("DepartmentName");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            PassportNumber = 1001,
                            Category = "Основна",
                            City = "Місто2",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Математика",
                            HireDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові1",
                            Name = "Ім'я1",
                            Position = "Викладач",
                            Street = "Вулиця 1",
                            Surname = "Прізвище1",
                            TIN = 5001,
                            WorkExperience = 1
                        },
                        new
                        {
                            PassportNumber = 1002,
                            Category = "Основна",
                            City = "Місто3",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Фізика",
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові2",
                            Name = "Ім'я2",
                            Position = "Викладач",
                            Street = "Вулиця 2",
                            Surname = "Прізвище2",
                            TIN = 5002,
                            WorkExperience = 2
                        },
                        new
                        {
                            PassportNumber = 1003,
                            Category = "Основна",
                            City = "Місто1",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Хімія",
                            HireDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові3",
                            Name = "Ім'я3",
                            Position = "Викладач",
                            Street = "Вулиця 3",
                            Surname = "Прізвище3",
                            TIN = 5003,
                            WorkExperience = 3
                        },
                        new
                        {
                            PassportNumber = 1004,
                            Category = "Основна",
                            City = "Місто2",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Біологія",
                            HireDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові4",
                            Name = "Ім'я4",
                            Position = "Викладач",
                            Street = "Вулиця 4",
                            Surname = "Прізвище4",
                            TIN = 5004,
                            WorkExperience = 4
                        },
                        new
                        {
                            PassportNumber = 1005,
                            Category = "Основна",
                            City = "Місто3",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Інформатика",
                            HireDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові5",
                            Name = "Ім'я5",
                            Position = "Викладач",
                            Street = "Вулиця 5",
                            Surname = "Прізвище5",
                            TIN = 5005,
                            WorkExperience = 5
                        },
                        new
                        {
                            PassportNumber = 1006,
                            Category = "Основна",
                            City = "Місто1",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Математика",
                            HireDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові6",
                            Name = "Ім'я6",
                            Position = "Викладач",
                            Street = "Вулиця 6",
                            Surname = "Прізвище6",
                            TIN = 5006,
                            WorkExperience = 6
                        },
                        new
                        {
                            PassportNumber = 1007,
                            Category = "Основна",
                            City = "Місто2",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Фізика",
                            HireDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові7",
                            Name = "Ім'я7",
                            Position = "Викладач",
                            Street = "Вулиця 7",
                            Surname = "Прізвище7",
                            TIN = 5007,
                            WorkExperience = 7
                        },
                        new
                        {
                            PassportNumber = 1008,
                            Category = "Основна",
                            City = "Місто3",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Хімія",
                            HireDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові8",
                            Name = "Ім'я8",
                            Position = "Викладач",
                            Street = "Вулиця 8",
                            Surname = "Прізвище8",
                            TIN = 5008,
                            WorkExperience = 8
                        },
                        new
                        {
                            PassportNumber = 1009,
                            Category = "Основна",
                            City = "Місто1",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Біологія",
                            HireDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові9",
                            Name = "Ім'я9",
                            Position = "Викладач",
                            Street = "Вулиця 9",
                            Surname = "Прізвище9",
                            TIN = 5009,
                            WorkExperience = 9
                        },
                        new
                        {
                            PassportNumber = 1010,
                            Category = "Основна",
                            City = "Місто2",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Інформатика",
                            HireDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові10",
                            Name = "Ім'я10",
                            Position = "Викладач",
                            Street = "Вулиця 10",
                            Surname = "Прізвище10",
                            TIN = 5010,
                            WorkExperience = 10
                        },
                        new
                        {
                            PassportNumber = 1011,
                            Category = "Основна",
                            City = "Місто3",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Математика",
                            HireDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові11",
                            Name = "Ім'я11",
                            Position = "Викладач",
                            Street = "Вулиця 11",
                            Surname = "Прізвище11",
                            TIN = 5011,
                            WorkExperience = 11
                        },
                        new
                        {
                            PassportNumber = 1012,
                            Category = "Основна",
                            City = "Місто1",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Фізика",
                            HireDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові12",
                            Name = "Ім'я12",
                            Position = "Викладач",
                            Street = "Вулиця 12",
                            Surname = "Прізвище12",
                            TIN = 5012,
                            WorkExperience = 12
                        },
                        new
                        {
                            PassportNumber = 1013,
                            Category = "Основна",
                            City = "Місто2",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Хімія",
                            HireDate = new DateTime(2014, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові13",
                            Name = "Ім'я13",
                            Position = "Викладач",
                            Street = "Вулиця 13",
                            Surname = "Прізвище13",
                            TIN = 5013,
                            WorkExperience = 13
                        },
                        new
                        {
                            PassportNumber = 1014,
                            Category = "Основна",
                            City = "Місто3",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Біологія",
                            HireDate = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові14",
                            Name = "Ім'я14",
                            Position = "Викладач",
                            Street = "Вулиця 14",
                            Surname = "Прізвище14",
                            TIN = 5014,
                            WorkExperience = 14
                        },
                        new
                        {
                            PassportNumber = 1015,
                            Category = "Основна",
                            City = "Місто1",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Інформатика",
                            HireDate = new DateTime(2012, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові15",
                            Name = "Ім'я15",
                            Position = "Викладач",
                            Street = "Вулиця 15",
                            Surname = "Прізвище15",
                            TIN = 5015,
                            WorkExperience = 15
                        },
                        new
                        {
                            PassportNumber = 1016,
                            Category = "Основна",
                            City = "Місто2",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Математика",
                            HireDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові16",
                            Name = "Ім'я16",
                            Position = "Викладач",
                            Street = "Вулиця 16",
                            Surname = "Прізвище16",
                            TIN = 5016,
                            WorkExperience = 16
                        },
                        new
                        {
                            PassportNumber = 1017,
                            Category = "Основна",
                            City = "Місто3",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Фізика",
                            HireDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові17",
                            Name = "Ім'я17",
                            Position = "Викладач",
                            Street = "Вулиця 17",
                            Surname = "Прізвище17",
                            TIN = 5017,
                            WorkExperience = 17
                        },
                        new
                        {
                            PassportNumber = 1018,
                            Category = "Основна",
                            City = "Місто1",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Хімія",
                            HireDate = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові18",
                            Name = "Ім'я18",
                            Position = "Викладач",
                            Street = "Вулиця 18",
                            Surname = "Прізвище18",
                            TIN = 5018,
                            WorkExperience = 18
                        },
                        new
                        {
                            PassportNumber = 1019,
                            Category = "Основна",
                            City = "Місто2",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Біологія",
                            HireDate = new DateTime(2008, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові19",
                            Name = "Ім'я19",
                            Position = "Викладач",
                            Street = "Вулиця 19",
                            Surname = "Прізвище19",
                            TIN = 5019,
                            WorkExperience = 19
                        },
                        new
                        {
                            PassportNumber = 1020,
                            Category = "Основна",
                            City = "Місто3",
                            ContractEndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ContractStartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Інформатика",
                            HireDate = new DateTime(2007, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsWarVeteran = false,
                            MiddleName = "По-батькові20",
                            Name = "Ім'я20",
                            Position = "Викладач",
                            Street = "Вулиця 20",
                            Surname = "Прізвище20",
                            TIN = 5020,
                            WorkExperience = 20
                        });
                });

            modelBuilder.Entity("Institute.Entity.PedagogicalLoadEntity", b =>
                {
                    b.Property<string>("Discipline")
                        .HasColumnType("text");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PassportNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HoursCount")
                        .HasColumnType("integer");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.HasKey("Discipline", "GroupNumber", "PassportNumber");

                    b.HasIndex("DepartmentName");

                    b.HasIndex("PassportNumber");

                    b.ToTable("PedagogicalLoads");

                    b.HasData(
                        new
                        {
                            Discipline = "Дисципліна1",
                            GroupNumber = 101,
                            PassportNumber = 1001,
                            DepartmentName = "Математика",
                            HoursCount = 40,
                            Semester = 1
                        },
                        new
                        {
                            Discipline = "Дисципліна2",
                            GroupNumber = 102,
                            PassportNumber = 1002,
                            DepartmentName = "Фізика",
                            HoursCount = 42,
                            Semester = 2
                        },
                        new
                        {
                            Discipline = "Дисципліна3",
                            GroupNumber = 103,
                            PassportNumber = 1003,
                            DepartmentName = "Хімія",
                            HoursCount = 44,
                            Semester = 3
                        },
                        new
                        {
                            Discipline = "Дисципліна4",
                            GroupNumber = 104,
                            PassportNumber = 1004,
                            DepartmentName = "Біологія",
                            HoursCount = 46,
                            Semester = 4
                        },
                        new
                        {
                            Discipline = "Дисципліна5",
                            GroupNumber = 105,
                            PassportNumber = 1005,
                            DepartmentName = "Інформатика",
                            HoursCount = 48,
                            Semester = 5
                        },
                        new
                        {
                            Discipline = "Дисципліна6",
                            GroupNumber = 106,
                            PassportNumber = 1006,
                            DepartmentName = "Математика",
                            HoursCount = 50,
                            Semester = 6
                        },
                        new
                        {
                            Discipline = "Дисципліна7",
                            GroupNumber = 107,
                            PassportNumber = 1007,
                            DepartmentName = "Фізика",
                            HoursCount = 52,
                            Semester = 7
                        },
                        new
                        {
                            Discipline = "Дисципліна8",
                            GroupNumber = 108,
                            PassportNumber = 1008,
                            DepartmentName = "Хімія",
                            HoursCount = 54,
                            Semester = 8
                        },
                        new
                        {
                            Discipline = "Дисципліна9",
                            GroupNumber = 109,
                            PassportNumber = 1009,
                            DepartmentName = "Біологія",
                            HoursCount = 56,
                            Semester = 1
                        },
                        new
                        {
                            Discipline = "Дисципліна10",
                            GroupNumber = 110,
                            PassportNumber = 1010,
                            DepartmentName = "Інформатика",
                            HoursCount = 58,
                            Semester = 2
                        },
                        new
                        {
                            Discipline = "Дисципліна11",
                            GroupNumber = 111,
                            PassportNumber = 1011,
                            DepartmentName = "Математика",
                            HoursCount = 60,
                            Semester = 3
                        },
                        new
                        {
                            Discipline = "Дисципліна12",
                            GroupNumber = 112,
                            PassportNumber = 1012,
                            DepartmentName = "Фізика",
                            HoursCount = 62,
                            Semester = 4
                        },
                        new
                        {
                            Discipline = "Дисципліна13",
                            GroupNumber = 113,
                            PassportNumber = 1013,
                            DepartmentName = "Хімія",
                            HoursCount = 64,
                            Semester = 5
                        },
                        new
                        {
                            Discipline = "Дисципліна14",
                            GroupNumber = 114,
                            PassportNumber = 1014,
                            DepartmentName = "Біологія",
                            HoursCount = 66,
                            Semester = 6
                        },
                        new
                        {
                            Discipline = "Дисципліна15",
                            GroupNumber = 115,
                            PassportNumber = 1015,
                            DepartmentName = "Інформатика",
                            HoursCount = 68,
                            Semester = 7
                        },
                        new
                        {
                            Discipline = "Дисципліна16",
                            GroupNumber = 116,
                            PassportNumber = 1016,
                            DepartmentName = "Математика",
                            HoursCount = 70,
                            Semester = 8
                        },
                        new
                        {
                            Discipline = "Дисципліна17",
                            GroupNumber = 117,
                            PassportNumber = 1017,
                            DepartmentName = "Фізика",
                            HoursCount = 72,
                            Semester = 1
                        },
                        new
                        {
                            Discipline = "Дисципліна18",
                            GroupNumber = 118,
                            PassportNumber = 1018,
                            DepartmentName = "Хімія",
                            HoursCount = 74,
                            Semester = 2
                        },
                        new
                        {
                            Discipline = "Дисципліна19",
                            GroupNumber = 119,
                            PassportNumber = 1019,
                            DepartmentName = "Біологія",
                            HoursCount = 76,
                            Semester = 3
                        },
                        new
                        {
                            Discipline = "Дисципліна20",
                            GroupNumber = 120,
                            PassportNumber = 1020,
                            DepartmentName = "Інформатика",
                            HoursCount = 78,
                            Semester = 4
                        });
                });

            modelBuilder.Entity("Institute.Entity.PhoneEmployeeEntity", b =>
                {
                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("PassportNumber")
                        .HasColumnType("integer");

                    b.HasKey("PhoneNumber", "PassportNumber");

                    b.HasIndex("PassportNumber");

                    b.ToTable("PhoneEmployees");

                    b.HasData(
                        new
                        {
                            PhoneNumber = "555-0101",
                            PassportNumber = 1001
                        },
                        new
                        {
                            PhoneNumber = "555-0102",
                            PassportNumber = 1001
                        },
                        new
                        {
                            PhoneNumber = "555-0103",
                            PassportNumber = 1002
                        },
                        new
                        {
                            PhoneNumber = "555-0104",
                            PassportNumber = 1002
                        },
                        new
                        {
                            PhoneNumber = "555-0105",
                            PassportNumber = 1003
                        },
                        new
                        {
                            PhoneNumber = "555-0106",
                            PassportNumber = 1003
                        },
                        new
                        {
                            PhoneNumber = "555-0107",
                            PassportNumber = 1004
                        },
                        new
                        {
                            PhoneNumber = "555-0108",
                            PassportNumber = 1004
                        },
                        new
                        {
                            PhoneNumber = "555-0109",
                            PassportNumber = 1005
                        },
                        new
                        {
                            PhoneNumber = "555-01010",
                            PassportNumber = 1005
                        },
                        new
                        {
                            PhoneNumber = "555-01011",
                            PassportNumber = 1006
                        },
                        new
                        {
                            PhoneNumber = "555-01012",
                            PassportNumber = 1006
                        },
                        new
                        {
                            PhoneNumber = "555-01013",
                            PassportNumber = 1007
                        },
                        new
                        {
                            PhoneNumber = "555-01014",
                            PassportNumber = 1007
                        },
                        new
                        {
                            PhoneNumber = "555-01015",
                            PassportNumber = 1008
                        },
                        new
                        {
                            PhoneNumber = "555-01016",
                            PassportNumber = 1008
                        },
                        new
                        {
                            PhoneNumber = "555-01017",
                            PassportNumber = 1009
                        },
                        new
                        {
                            PhoneNumber = "555-01018",
                            PassportNumber = 1009
                        },
                        new
                        {
                            PhoneNumber = "555-01019",
                            PassportNumber = 1010
                        },
                        new
                        {
                            PhoneNumber = "555-01020",
                            PassportNumber = 1010
                        },
                        new
                        {
                            PhoneNumber = "555-01021",
                            PassportNumber = 1011
                        },
                        new
                        {
                            PhoneNumber = "555-01022",
                            PassportNumber = 1011
                        },
                        new
                        {
                            PhoneNumber = "555-01023",
                            PassportNumber = 1012
                        },
                        new
                        {
                            PhoneNumber = "555-01024",
                            PassportNumber = 1012
                        },
                        new
                        {
                            PhoneNumber = "555-01025",
                            PassportNumber = 1013
                        },
                        new
                        {
                            PhoneNumber = "555-01026",
                            PassportNumber = 1013
                        },
                        new
                        {
                            PhoneNumber = "555-01027",
                            PassportNumber = 1014
                        },
                        new
                        {
                            PhoneNumber = "555-01028",
                            PassportNumber = 1014
                        },
                        new
                        {
                            PhoneNumber = "555-01029",
                            PassportNumber = 1015
                        },
                        new
                        {
                            PhoneNumber = "555-01030",
                            PassportNumber = 1015
                        },
                        new
                        {
                            PhoneNumber = "555-01031",
                            PassportNumber = 1016
                        },
                        new
                        {
                            PhoneNumber = "555-01032",
                            PassportNumber = 1016
                        },
                        new
                        {
                            PhoneNumber = "555-01033",
                            PassportNumber = 1017
                        },
                        new
                        {
                            PhoneNumber = "555-01034",
                            PassportNumber = 1017
                        },
                        new
                        {
                            PhoneNumber = "555-01035",
                            PassportNumber = 1018
                        },
                        new
                        {
                            PhoneNumber = "555-01036",
                            PassportNumber = 1018
                        },
                        new
                        {
                            PhoneNumber = "555-01037",
                            PassportNumber = 1019
                        },
                        new
                        {
                            PhoneNumber = "555-01038",
                            PassportNumber = 1019
                        },
                        new
                        {
                            PhoneNumber = "555-01039",
                            PassportNumber = 1020
                        },
                        new
                        {
                            PhoneNumber = "555-01040",
                            PassportNumber = 1020
                        });
                });

            modelBuilder.Entity("Institute.Entity.ReferencesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("PassportNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PassportNumber");

                    b.ToTable("References");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            PassportNumber = 1001,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            PassportNumber = 1002,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            PassportNumber = 1003,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            PassportNumber = 1004,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            PassportNumber = 1005,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            PassportNumber = 1006,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            PassportNumber = 1007,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            PassportNumber = 1008,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            PassportNumber = 1009,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            PassportNumber = 1010,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            PassportNumber = 1011,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            PassportNumber = 1012,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            PassportNumber = 1013,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            PassportNumber = 1014,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            PassportNumber = 1015,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            PassportNumber = 1016,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            PassportNumber = 1017,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            PassportNumber = 1018,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            PassportNumber = 1019,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            PassportNumber = 1020,
                            ReferenceType = "Загальна",
                            ReleaseDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Institute.Entity.VacationEntity", b =>
                {
                    b.Property<string>("VacationType")
                        .HasColumnType("text");

                    b.Property<int>("PassportNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VacationType", "PassportNumber");

                    b.HasIndex("PassportNumber");

                    b.ToTable("Vacations");

                    b.HasData(
                        new
                        {
                            VacationType = "Щорічна відпустка1",
                            PassportNumber = 1001,
                            EndDate = new DateTime(2027, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка2",
                            PassportNumber = 1002,
                            EndDate = new DateTime(2026, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка3",
                            PassportNumber = 1003,
                            EndDate = new DateTime(2026, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка4",
                            PassportNumber = 1004,
                            EndDate = new DateTime(2026, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка5",
                            PassportNumber = 1005,
                            EndDate = new DateTime(2026, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка6",
                            PassportNumber = 1006,
                            EndDate = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка7",
                            PassportNumber = 1007,
                            EndDate = new DateTime(2026, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка8",
                            PassportNumber = 1008,
                            EndDate = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка9",
                            PassportNumber = 1009,
                            EndDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка10",
                            PassportNumber = 1010,
                            EndDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка11",
                            PassportNumber = 1011,
                            EndDate = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка12",
                            PassportNumber = 1012,
                            EndDate = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка13",
                            PassportNumber = 1013,
                            EndDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка14",
                            PassportNumber = 1014,
                            EndDate = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка15",
                            PassportNumber = 1015,
                            EndDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка16",
                            PassportNumber = 1016,
                            EndDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка17",
                            PassportNumber = 1017,
                            EndDate = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка18",
                            PassportNumber = 1018,
                            EndDate = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка19",
                            PassportNumber = 1019,
                            EndDate = new DateTime(2025, 7, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VacationType = "Щорічна відпустка20",
                            PassportNumber = 1020,
                            EndDate = new DateTime(2025, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Institute.Entity.EmployeeEntity", b =>
                {
                    b.HasOne("Institute.Entity.DepartmentEntity", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Institute.Entity.PedagogicalLoadEntity", b =>
                {
                    b.HasOne("Institute.Entity.DepartmentEntity", "Department")
                        .WithMany("PedagogicalLoads")
                        .HasForeignKey("DepartmentName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Institute.Entity.EmployeeEntity", "Employee")
                        .WithMany("PedagogicalLoads")
                        .HasForeignKey("PassportNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Institute.Entity.PhoneEmployeeEntity", b =>
                {
                    b.HasOne("Institute.Entity.EmployeeEntity", "Employee")
                        .WithMany("PhoneEmployees")
                        .HasForeignKey("PassportNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Institute.Entity.ReferencesEntity", b =>
                {
                    b.HasOne("Institute.Entity.EmployeeEntity", "Employee")
                        .WithMany("References")
                        .HasForeignKey("PassportNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Institute.Entity.VacationEntity", b =>
                {
                    b.HasOne("Institute.Entity.EmployeeEntity", "Employee")
                        .WithMany("Vacations")
                        .HasForeignKey("PassportNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Institute.Entity.DepartmentEntity", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("PedagogicalLoads");
                });

            modelBuilder.Entity("Institute.Entity.EmployeeEntity", b =>
                {
                    b.Navigation("PedagogicalLoads");

                    b.Navigation("PhoneEmployees");

                    b.Navigation("References");

                    b.Navigation("Vacations");
                });
#pragma warning restore 612, 618
        }
    }
}
